version: '3'

services:
  database:
    image: mysql:8.0.13
    container_name: tourney-mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - go-tourney-network

  app:
    image: go-tourney:1.0
    container_name: go-tourney
    working_dir: /go/src/go-tourney
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - go-tourney-network

networks:
  go-tourney-network:
    driver: "bridge"

volumes:
  mysql-data:
