apiVersion: v1
kind: Service
metadata:
  name: go-tourney
  labels:
    app: go-tourney
spec:
  ports:
    - port: 8080
  selector:
    app: go-tourney
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-tourney-deployment
  labels:
    app: go-tourney
spec:
  selector:
    matchLabels:
      app: go-tourney
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: go-tourney
        tier: frontend
    spec:
      containers:
      - name: go-tourney
        image: macox/go-tourney:1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 8080
          name: go-tourney
